version: "3"
services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=123456Cloud
  web:
    image: melisa/node-web-app
    command: node ./src/index
    ports:
      - 5000:5000
volumes:
    esdata1:
      driver: local